name: Build and publish

on:
  push:
    tags: 
      - v[1-9]+.[0-9]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest 

    env:
      Solution_Name: testUpos.sln
  
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
   
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1
    
    - name: Execute unit tests
      run: dotnet test
    
    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:RestorePackagesConfig=true /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
   
    - name: Build the application
      run: msbuild $env:Solution_Name /p:Configuration=$env:Configuration /p:UapAppxPackageBuildMode=$env:Appx_Package_Build_Mode /p:AppxBundle=$env:Appx_Bundle
      env:
        Appx_Bundle: Always
        Appx_Bundle_Platforms: x86|x64
        Appx_Package_Build_Mode: StoreUpload
        Configuration: ${{ matrix.configuration }}

    - name: Rename zip
      run:  Rename-Item -Path .\testUpos\testUpos.zip -NewName testUpos_${{ github.ref_name }}.zip
      
    - name: Publish
      uses: ncipollo/release-action@v1
      with:
        artifacts: "testUpos/testUpos_${{ github.ref_name }}.zip"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
